name: Lint, Build, and Deploy to Netlify

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  lint-build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Validate HTML files
      - name: Lint HTML files
        uses: chrisgladd/html-validate-action@v1.1
        with:
          path: "./"  # Validate all HTML files in the repository

      # Step 3: Lint CSS files
      - name: Lint CSS files
        uses: stylelint/stylelint-action@v2
        with:
          files: "**/*.css"

      # Step 4: Lint JavaScript files
      - name: Lint JavaScript files
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          eslint_flags: "."  # Target all JavaScript files in the repo

      # Step 5: Deploy to Netlify
      - name: Deploy to Netlify
        uses: netlify/actions/cli@v4
        with:
          args: deploy --dir=./ --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
